name: test

on:
  workflow_call:
    outputs:
      image:
        description: "The first output string"
        value: ${{ jobs.test.outputs.image }}

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build_wrapper.outputs.image }}
    steps:
      - id: build_wrapper
        uses: bimitshah/workflows/test-build@main
