name: test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntun-latest
    outputs:
      name_wrapper: ${{ steps.build_wrapper.outputs.name }}
    steps:
      - id: build_wrapper
        uses: bimitshah/workflows/test-build@main
